config/routes.rb
Holdme2it::Application.routes.draw do

  post 'invitations/create', as: :create_invitation
  get 'invitations/:key/view' => 'invitations#view', as: :view_invitation
  get 'invitations/:key/accept' => 'invitations#accept', as: :accept_invitation
  get 'invitations/:key/cancel' => 'invitations#cancel', as: :cancel_invitation

  #resources :invitations

  get 'lists/show'  => 'lists#show', as: :lists
  get 'lists/data/:id'  => 'lists#data'
  resources :lists
 
  devise_for :users, skip: [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get "static/index"

  root :to => 'static#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :user_id, :day, :list_items, :list_items_attributes

  validates :user_id, :presence=>true

  belongs_to :user#, :class_name => :User#, :foreign_key=>:user_id
  has_many :list_items
  has_many :incomplete_list_items, :class_name=>'ListItem', :foreign_key=> :list_id, :conditions=> { done: false }

  accepts_nested_attributes_for :list_items, :reject_if => proc { |a| a['name'].blank? }, :allow_destroy => true

  def nice_format_day
  	case self.day
  	when Date.today
  		"today"
  	else
  		self.day
  	end
  end
end

app/controllers/lists_controller.rb
class ListsController < InheritedResources::Base
	before_filter :authenticate_user!

	def show
		@user=current_user
		@partner=current_user.partner

		@sent_invitations = current_user.sent_invitations.reject{|i| i.status=="cancelled"}
	end

	def update
		@list = List.find(params[:id])
		if @list.update_attributes(params[:list])
		  redirect_to lists_path, :notice  => "Successfully updated list."
		else
		  render :action => 'edit'
		end
	end

	def data
		if params[:id] && List.find(params[:id])
			list=List.find(params[:id])
			render '_list', :locals=>{:list=>list, :@removable=>(user_signed_in? && current_user.current_list.id==list.id)}, :layout=>false
		else
			render :nothing
		end
	end
end

app/helpers/lists_helper.rb
module ListsHelper

	def new_invitation
		Invitation.new()
	end

end

app/views/lists/_list.html.erb
<%= simple_form_for(list, :remote=>true) do |f| %>

	<h3><%= list.user.first_name %>'s to do list</h3>

	<% if user_signed_in? && list.user==current_user %>
		<%= link_to_add_fields "Add something!", f, :list_items %>
	<% else %>
		<div style="height:9px;width:100%"></div>
	<% end %>
	<%= f.submit "Save list!", :class=>"btn btn-success pull-right" if @removable %>

	<br/><br/>
	<%= f.fields_for :list_items do |ff| %>
		<%#= ff.input :name %>
		<%= render 'lists/list_item_fields', :f=>ff %>
	<% end %>
<% end %>

app/views/lists/_list_item_fields.html.erb
<div class="fields">

	<%= f.input :done, :label=>false, :wrapper=>false, :disabled=>!@removable %>
    <%= f.input :name, :label=>false, :wrapper=>false, input_html: { style: "width:280px!important" } , :disabled=>!@removable%>
    <%= link_to_remove_fields "remove", f if @removable %>

</div>

app/views/lists/show.html.erb
<h2>Welcome to your to do list console!</h2>

<div class="row">
	<div class="span6 list">
		<div id="list<%= @user.current_list.id %>" class="list_inset">
			<%= render 'list', :list=>@user.current_list, :@removable=>true %>
		</div>
	</div>

	<div class="span6 list">
		<% if @partner %>
			<div id="list<%= @partner.current_list.id %>" class="list_inset">
				<%= render 'list', :list=>@partner.current_list, :@removable=>false %>
			</div>
		<% elsif @invitation %>
			*/ the user has followed an invitation link, let them accept it
			<%= link_to "Accept #{@inviter.first_name}'s invitation!", accept_invitation_path(@invitation.key) %>
		<% else %>
			<%= render 'invitations/invite' %>
		<% end %> 
	</div>
</div>

<div class="row">
	<div class="span12">
		<h3>The chat zone</h3>

	</div>
</div>

<script>

  function update()
  { 
	<% if @partner %>
		$.get('/lists/data/<%= current_user.partner.current_list.id %>', function(data)
		{
		 $('#list<%= current_user.partner.current_list.id %>').html(data);
		});
	<% end %>
  }

$(document).ready(function($){
  window.setInterval('update()', 10*1000);
});
</script>