config/routes.rb
Holdme2it::Application.routes.draw do

  post 'invitations/create', as: :create_invitation
  get 'invitations/:key/view' => 'invitations#view', as: :view_invitation
  get 'invitations/:key/accept' => 'invitations#accept', as: :accept_invitation
  get 'invitations/:key/cancel' => 'invitations#cancel', as: :cancel_invitation

  #resources :invitations

  get 'lists/show'  => 'lists#show', as: :lists
  get 'lists/data/:id'  => 'lists#data'
  resources :lists
 
  devise_for :users, skip: [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get "static/index"

  root :to => 'static#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  attr_accessible :friends_email, :key, :status, :user_id, :friend_id

  belongs_to :user
  belongs_to :friend
  before_create :create_key
  after_create :email_friend

  validates :friends_email, :presence=>true, :email => true

  state_machine :status, :initial => :init do
    before_transition :init => :sent, :do => :send_invitation_email
    before_transition :any => :accepted, :do => :send_accepted_email

    event :email_friend do
      transition :init => :sent
    end

  	event :accept do
      transition any => :accepted
  	end

    event :cancel do
      transition any => :cancelled
    end
  end

	def create_key
		random_hex = SecureRandom.hex(6)

		while Invitation.find_by_key("1X#{random_hex}") != nil
			random_hex = SecureRandom.hex(6)
		end

		self.key="1X#{random_hex}"
	end

	def send_invitation_email
		UserNotifier.send_invitation_email(self).deliver
	end

  def send_accepted_email
    UserNotifier.send_accepted_email(self).deliver
  end

  def accept(acceptors_id)

    @invitor = self.user
    @acceptor = User.find(acceptors_id)

    @invitor.partner=@acceptor
    @acceptor.partner=@invitor
    
    @invitor.save
    @acceptor.save

    super

    #puts "#{@acceptor.first_name} just accepted #{user.first_name}'s invitation"
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < InheritedResources::Base
before_filter :authenticate_user!, :only=> [:create, :accept, :cancel]

	def create
		@friends_email=params[:invitation][:friends_email]

		if @friends_email == current_user.email
			flash[:error]="You can't invite yourself, silly!"
		else

			@invitation = Invitation.new(:friends_email=>@friends_email, :user_id => current_user.id)
			if @invitation.save
				flash[:notice]="Thanks, we've invited your friend!"
				UserNotifier.send_invitation_email(@invitation).deliver
			else
				flash[:error]="There was a problem inviting your friend."
			end
		end

		redirect_to lists_path
	end

	def view
		#redirects to the lists page from where the user can create their account

		@invitation = Invitation.find_by_key(params[:key]) if params[:key]

		if @invitation
			case @invitation.status 
			when "sent"
				if user_signed_in?
					redirect_to lists_path
				end
			when "cancelled"
				flash[:error]="Sorry, but that invitation's been cancelled!"
				redirect_to root_path
			when "accepted"
				flash[:error]="Sorry, but that invitation's already been accepted!"
				redirect_to root_path
			end
		else
			flash[:error]="Sorry, that link doesn't seem to be valid."
			redirect_to root_path
		end
	end

	def accept
		@invitation = Invitation.find_by_key(params[:key]) if params[:key]

		if @invitation && (current_user.invitation == @invitation || current_user.email == @invitation.friends_email)
			@invitation.accept(current_user.id)
			flash[:success]="You've accepted #{@invitation.user.first_name}'s invitation!"
			redirect_to lists_path
		else
			flash[:error]="Sorry, that link doesn't seem to be valid."
			redirect_to root_path
		end
	end

	def cancel
		@invitation = Invitation.find_by_key(params[:key]) if params[:key]

		if @invitation && current_user == @invitation.user
			@invitation.cancel
			redirect_to lists_path
			flash[:success]="We've cancelled that invitation - the link will no longer work."
		else
			flash[:error]="Sorry, that link doesn't seem to be valid."
			redirect_to lists_path
		end
	end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= simple_form_for(new_invitation, :url=>create_invitation_path) do |f| %>
  
	<div class="row">
		<div class="span3">
    		<%= f.input :friends_email, :label=>false, :placeholder=>"your friend's email", :html_attributes=>{:placeholder=>"test"} %>
    	</div>

    	<div class="span pull-right">
    		<%= f.submit "Send invite!", :class=>'btn btn-success' %>
    	</div>
    </div>

<% end %>

app/views/invitations/_invite.html.erb
<h3>Invite a friend to get started!</h3>
<%= render 'invitations/form' %>

<% if @sent_invitations %>
	<ul>
		<% @sent_invitations.each do |invite| %>
			<li>
				<%= invite.friends_email %>
				<%= link_to "Cancel", cancel_invitation_path(invite.key) %>
			</li>
		<% end %>
	</ul>
<% end %>

app/views/invitations/_modal_sign_up.html.erb
<div id="Modal_sign_up" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <%= simple_form_for((User.new), :as => resource_name, :url => registration_path(resource_name)) do |f| %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">One more step!</h3>
    </div>
    <div class="modal-body" style="text-align:center">
      <p>You'll need to create an account so that we remember you for next time.</p>

        <div style="margin:0 auto;">

          <%= f.input :first_name, autofocus: true %>
          <%= f.input :last_name %>

          <%= f.input :invitation_id, :as => :hidden, :input_html => { :value => @invitation.id }%>

          <%= f.input :email, :label => "Email", :value=> @invitation.friends_email %>
          <%= f.input :password, :label => "Password" %>

        </div>

    </div>
    <div class="modal-footer" style="text-align:center">
      <%= f.button :submit, "Get started and join in!", :class => "btn btn-large btn-success" %>
    </div>
  <% end %>
</div>

app/views/invitations/view.html.erb
<h2>Welcome to your to do list console!!</h2>

<div class="row">
	<div class="span6 list" style="background:url('/assets/paper1.png')">
		<div class="span6">
			<div style="margin-left:100px">
				<a href="#Modal_sign_up" role="button" class="btn btn-large btn-success" data-toggle="modal" style="margin-top:8px">Start your own to do list!</a>
			</div>
		</div>
	</div>

	<div class="span6 list" style="background:url('/assets/paper2.png')">
		<%= render 'lists/list', :list=>@invitation.user.current_list %>
	</div>
</div>

<div class="row">
	<div class="span12">
		<h3>The chat zone</h3>

	</div>
</div>


<%= render 'modal_sign_up' %>