config/routes.rb
Holdme2it::Application.routes.draw do

  post 'invitations/create', as: :create_invitation
  get 'invitations/:key/view' => 'invitations#view', as: :view_invitation
  get 'invitations/:key/accept' => 'invitations#accept', as: :accept_invitation
  get 'invitations/:key/cancel' => 'invitations#cancel', as: :cancel_invitation

  #resources :invitations

  get 'lists/show'  => 'lists#show', as: :lists
  get 'lists/data/:id'  => 'lists#data'
  resources :lists
 
  devise_for :users, skip: [:sessions]

  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete '/logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end
  
  get "static/index"

  root :to => 'static#index'

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
<div id="footer" class="navbar-static-bottom">
  <div class="container">
  	
    <div class="row">
      <div class="span4 v_offset">
        <% if user_signed_in? %>
        We think you're awesome.
        <% else %> 
        <%= link_to "Sign up today", new_user_registration_path %>. You know you want to.
        <% end %>
      </div>

      <div class="span4 terms">
        <div>
        <%#= link_to "Terms and Conditions", tos_path %>
        </div>
        <div>
        <%#= link_to "Privacy Policy", privacy_path %>
        </div>
        <div>
        <%#= link_to "For Businesses", business_path %>
        </div>
      </div>
      <div class="span social pull-right">

      <%= facebook_link %>
      <%= twitter_link %>

      <%#= link_to "or contact us directly", contact_path %>

      </div>

      

    </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-static-top" id="header">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to(image_tag("logo.png", :class => "logo"), root_path, :class=> "brand") %>
      <ul class="nav v_offset">
        <li>
          <%= link_to "My list for today", lists_path %>
        </li>

        <li>
          <%= link_to "How it works", root_path %>
        </li>
      </ul>

      <div class="pull-right header_right">
        <ul class="nav sign_in_links v_offset">
          <% if user_signed_in? %>
            <li><%= link_to "My account", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Holdme2it</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrap"> <%# this is for the footer rendering %>
<%= render 'layouts/header' %>
	<div id="push-top"></div>
	
	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
			<button class="close" data-dismiss="alert">x</button>
			<%= message %>
			</div>
		<% end %>
	</div>

	<div class="container" style="margin-bottom:25px">
		<%= yield %>
	</div>

	<div id="push-bottom"></div>
</div>

<%= render 'layouts/footer' %>
<%#= render 'layouts/third_party/google_analytics' %>

</body>
</html>

app/views/layouts/table_email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><%= yield :title %></title>
        <%= render 'style' %>
    </head>
    <body leftmargin="0" marginwidth="0" topmargin="0" marginheight="0" offset="0">
        <center>
            <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable">
                <tr>
                    <td align="center" valign="top" id="bodyCell">
                        <!-- BEGIN TEMPLATE // -->
                        <table border="0" cellpadding="0" cellspacing="0" id="templateContainer">
                                <td align="center" valign="top">
                                    <!-- BEGIN HEADER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateHeader">
                                        <tr>
                                            <td valign="top" class="headerContent">
                                                <%#= yield :header %>
                                                <img src="http://holdme2it.herokuapp.com/assets/logo-45d7de77736a52a98db19455d757ebfe.png" style="max-width:600px;" id="headerImage" mc:label="header_image" mc:edit="header_image" mc:allowdesigner mc:allowtext />
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END HEADER -->
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">
                                    <!-- BEGIN BODY // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateBody">
                                        <tr>
                                            <td valign="top" class="bodyContent" mc:edit="body_content">
                                                <%= yield %>                                              
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END BODY -->
                                </td>
                            </tr>
                            <tr>
                                <td align="center" valign="top">
                                    <!-- BEGIN FOOTER // -->
                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateFooter">
                                        <tr>
                                            <td valign="top" class="footerContent" mc:edit="footer_content00">
                                                <%= link_to "Follow on Facebook", Settings.facebook_url %>&nbsp;&nbsp;&nbsp;<%#= link_to "Follow on Twitter", Settings.twitter_url %>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top" class="footerContent" style="padding-top:0;" mc:edit="footer_content01">
                                                <em>Copyright &copy; <%= Date.today.year %> Michael Dawson Enterprises Pty Ltd, All rights reserved.</em>
                                                <br />
                                                
                                                <strong>Our mailing address is:</strong>
                                                <br />
                                                <%= Settings.business_address %>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td valign="top" class="footerContent" style="padding-top:0; padding-bottom:40px;" mc:edit="footer_content02">
                                                <%#= link_to "manage email subscriptions", subscriptions_url(@user.key) %>&nbsp;&nbsp;&nbsp;<%#= link_to "unsubscribe", unsubscribe_url(@user.key) %>&nbsp;
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- // END FOOTER -->
                                </td>
                            </tr>
                        </table>
                        <!-- // END TEMPLATE -->
                    </td>
                </tr>
            </table>
        </center>
    </body>
</html>